const data: any = {
  "products": [
    {
      "imgURL": `images/clothe_1.png`,
      "name": "TODELT SÆT",
      "description": "Jakke Og Bukser",
      "brand": "Leyton™",
      "quantity": 1,
      "stock": 5,
      "size": "md",
      "sizeName": "Medium",
      "color": "#B8C0CA",
      "colorName": "Blå",
      "variant": "",
      "price": 334.95,
      "originalPrice": 596.30,
      "discount": "",
      "grade": 4.5,
      "reviews": 1971
    },
    {
      "imgURL": `images/accessories_4.jpeg`,
      "name": "Backpack Bag",
      "description": "Pink Cake",
      "brand": "Local™",
      "quantity": 1,
      "stock": 2,
      "size": "",
      "sizeName": "Small",
      "color": "pink",
      "colorName": "Pink",
      "variant": "",
      "price": 220.95,
      "originalPrice": 436.55,
      "discount": "",
      "grade": 4,
      "reviews": 837
    },
    {
      "imgURL": `images/clothes_3.jpeg`,
      "name": "TShirt",
      "description": "",
      "brand": "Leyton™",
      "quantity": 1,
      "stock": 8,
      "size": "",
      "sizeName": "Medium",
      "color": "#B8C0CA",
      "colorName": "Blå",
      "variant": "",
      "price": 98.95,
      "originalPrice": 127.85,
      "discount": "",
      "grade": 3.5,
      "reviews": 434
    },
    {
      "imgURL": `images/accessories_7.jpeg`,
      "name": "Rossa Glasses",
      "description": "Goldener Stab",
      "brand": "Brand™",
      "quantity": 1,
      "stock": 12,
      "size": "",
      "sizeName": "Einheitsgröße",
      "color": "pink",
      "colorName": "Pink",
      "variant": "",
      "price": 37.95,
      "originalPrice": 86.35,
      "discount": "",
      "grade": 5,
      "reviews": 1523
    },
  ]
}

export default data